# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai_agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61i_agent.proto\x12\x08\x61i_agent\".\n\x10SummarizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04line\x18\x02 \x01(\x05\"!\n\x11SummarizeResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2R\n\nSummarizer\x12\x44\n\tSummarize\x12\x1a.ai_agent.SummarizeRequest\x1a\x1b.ai_agent.SummarizeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUMMARIZEREQUEST']._serialized_start=28
  _globals['_SUMMARIZEREQUEST']._serialized_end=74
  _globals['_SUMMARIZERESPONSE']._serialized_start=76
  _globals['_SUMMARIZERESPONSE']._serialized_end=109
  _globals['_SUMMARIZER']._serialized_start=111
  _globals['_SUMMARIZER']._serialized_end=193
# @@protoc_insertion_point(module_scope)
