# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import summarizer_pb2 as summarizer__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in summarizer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SummarizerServiceStub(object):
    """service defination always remains one and defines the gRPC service
    ig similar to making the instace of service in the class for DI
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Summarize = channel.unary_unary(
                '/summarizer.SummarizerService/Summarize',
                request_serializer=summarizer__pb2.SummarizerRequest.SerializeToString,
                response_deserializer=summarizer__pb2.SummarizerResponse.FromString,
                _registered_method=True)
        self.Calculate = channel.unary_unary(
                '/summarizer.SummarizerService/Calculate',
                request_serializer=summarizer__pb2.CalculateResponse.SerializeToString,
                response_deserializer=summarizer__pb2.CalculateResponse.FromString,
                _registered_method=True)


class SummarizerServiceServicer(object):
    """service defination always remains one and defines the gRPC service
    ig similar to making the instace of service in the class for DI
    """

    def Summarize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Calculate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SummarizerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Summarize': grpc.unary_unary_rpc_method_handler(
                    servicer.Summarize,
                    request_deserializer=summarizer__pb2.SummarizerRequest.FromString,
                    response_serializer=summarizer__pb2.SummarizerResponse.SerializeToString,
            ),
            'Calculate': grpc.unary_unary_rpc_method_handler(
                    servicer.Calculate,
                    request_deserializer=summarizer__pb2.CalculateResponse.FromString,
                    response_serializer=summarizer__pb2.CalculateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'summarizer.SummarizerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('summarizer.SummarizerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SummarizerService(object):
    """service defination always remains one and defines the gRPC service
    ig similar to making the instace of service in the class for DI
    """

    @staticmethod
    def Summarize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/summarizer.SummarizerService/Summarize',
            summarizer__pb2.SummarizerRequest.SerializeToString,
            summarizer__pb2.SummarizerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Calculate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/summarizer.SummarizerService/Calculate',
            summarizer__pb2.CalculateResponse.SerializeToString,
            summarizer__pb2.CalculateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
