# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: summarizer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'summarizer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10summarizer.proto\x12\nsummarizer\"!\n\x11SummarizerRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"%\n\x12SummarizerResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t\"F\n\x10\x43\x61lculateRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\x12\t\n\x01\x63\x18\x03 \x01(\x05\x12\x11\n\toperation\x18\x04 \x01(\t\"#\n\x11\x43\x61lculateResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\xaa\x01\n\x11SummarizerService\x12J\n\tSummarize\x12\x1d.summarizer.SummarizerRequest\x1a\x1e.summarizer.SummarizerResponse\x12I\n\tCalculate\x12\x1d.summarizer.CalculateResponse\x1a\x1d.summarizer.CalculateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'summarizer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUMMARIZERREQUEST']._serialized_start=32
  _globals['_SUMMARIZERREQUEST']._serialized_end=65
  _globals['_SUMMARIZERRESPONSE']._serialized_start=67
  _globals['_SUMMARIZERRESPONSE']._serialized_end=104
  _globals['_CALCULATEREQUEST']._serialized_start=106
  _globals['_CALCULATEREQUEST']._serialized_end=176
  _globals['_CALCULATERESPONSE']._serialized_start=178
  _globals['_CALCULATERESPONSE']._serialized_end=213
  _globals['_SUMMARIZERSERVICE']._serialized_start=216
  _globals['_SUMMARIZERSERVICE']._serialized_end=386
# @@protoc_insertion_point(module_scope)
